### ISSUE TITLE
Upgrade django-solo

### ISSUE THREAD

**Issue by cyberbudy** [jamiecounsell/django-des#1]
django-solo has been updated to 1.1.3

**Comment by jamiecounsell** [comment]
Thanks for the PR @cyberbudy. This has been deployed to PIP as 2.3.0.

**Comment by cyberbudy** [comment]
I've missed that django-solo was also specified in setup.py

**Comment by jamiecounsell** [comment]
@cyberbudy ahh yes. Patched in 2.4.1.

**Comment by cyberbudy** [comment]
Thanks!
